### ISSUE TITLE
Orderedhash fucks with Hash#to_yaml

### ISSUE THREAD

**Issue by chrislloyd** [quackingduck-archive/exemplor#2]
Is it really necessary?

**Comment by quackingduck** [comment]
Can you provide an example?

OrderedHash ensures deterministic output.

**Comment by chrislloyd** [comment]
http://gist.github.com/213096

**Comment by chrislloyd** [comment]
Sorry, I found it when I was using a Hash. Could you just order it in an array?

**Comment by quackingduck** [comment]
Go to: http://railsapi.com/doc/rails-v2.3.4_ruby-v1.9/

Type "to_yaml" in the search box. Notice something the signature of _every other_ to_yaml method?

Closed. Resolution: pebkac
